// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXvt3ICqKMulzklVfPBw_SFIVdSlb8hTw',
    appId: '1:990650286607:web:340a768117c868394c997a',
    messagingSenderId: '990650286607',
    projectId: 'groovy-student-419204',
    authDomain: 'groovy-student-419204.firebaseapp.com',
    storageBucket: 'groovy-student-419204.firebasestorage.app',
    measurementId: 'G-PEP7S5BFJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX8LULcDuiLn7FdsbM5iYej90qs39yxm8',
    appId: '1:990650286607:android:c2a9e317e5ca1c3e4c997a',
    messagingSenderId: '990650286607',
    projectId: 'groovy-student-419204',
    storageBucket: 'groovy-student-419204.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI-VWd8ZhoRzww-luj7oAtXy7EXzcXmSE',
    appId: '1:990650286607:ios:36ae5b7795a45fa34c997a',
    messagingSenderId: '990650286607',
    projectId: 'groovy-student-419204',
    storageBucket: 'groovy-student-419204.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI-VWd8ZhoRzww-luj7oAtXy7EXzcXmSE',
    appId: '1:990650286607:ios:36ae5b7795a45fa34c997a',
    messagingSenderId: '990650286607',
    projectId: 'groovy-student-419204',
    storageBucket: 'groovy-student-419204.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXvt3ICqKMulzklVfPBw_SFIVdSlb8hTw',
    appId: '1:990650286607:web:99320bbd23b96b8e4c997a',
    messagingSenderId: '990650286607',
    projectId: 'groovy-student-419204',
    authDomain: 'groovy-student-419204.firebaseapp.com',
    storageBucket: 'groovy-student-419204.firebasestorage.app',
    measurementId: 'G-L2DD1JMVTK',
  );
}
